##############################################################################
spring:
  application:
    name: zhpt-service
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: zhpt

  servlet:                     #限制上传文件大小
      multipart:
        max-file-size: 100MB
        max-request-size: 500MB

  cloud:
    cros:
      allow-origin: 127.0.0.1,localhost
server:
  port: 8081

#################################################################################
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://128.160.185.140:8101/eureka

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true


##############################################################################
zhpt:
    cloud:
      resources:
        jdbc:
          locations: jdbc.properties
        redis:
          locations: redis.properties

##############################################################################
mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.cloud.zhpt.*.entity
  mapper-locations: classpath*:com/cloud/zhpt/*/*/mapper/*.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


###############################################################################
logging:
  config: classpath:log4j2.xml

###############################登录验证码验证开关###############################################
login:
  captcha: false










