spring:
  application:
    name: zhpt

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.3:8101/eureka

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

zhpt:
    cloud:
      resources:
        locations: jdbc.properties

mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.cloud.sw.entity
  mapper-locations: /**/mapper/*.xml

logging:
  config: classpath:log4j2.xml



